version: 2
jobs:
  build:
    docker:
      - image: sodesign/ci:latest
    working_directory: /root/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - @@NAME@@-v1-{{ .Branch }}-{{ checksum "front/yarn.lock" }}-{{ checksum "back/composer.lock" }}

      - run:
          name: Yarn
          command: |
            cd front
            yarn || (rm -rf node_modules && npm install)
      - run:
          name: Composer
          command: |
            cd back
            composer selfupdate
            composer install
      - run:
          name: Build front
          command: |
            cd front
            yarn build

      - save_cache:
          key: @@NAME@@-v1-{{ .Branch }}-{{ checksum "front/yarn.lock" }}-{{ checksum "back/composer.lock" }}
          paths:
            - front/node_modules
            - back/vendor

      - deploy:
          name: Prepare deploy
          command: |
            mkdir -p deploy
            cp -R front/dist deploy/front
            cp -R back deploy/back
            cp front/dist/rev-manifest.json deploy/back
            mkdir back/site/assets/tmp
      - deploy:
          name: Deploy
          command: |
            set -e
            if   [ "$CIRCLE_BRANCH" == "master"  ]; then
              /root/deploy @@NAME@@
            elif [ "$CIRCLE_BRANCH" == "develop" ]; then
              /root/deploy staging
            fi
