version: 2
jobs:
  build:
    docker:
      - image: node:6.10.2
    working_directory: ~/generator

    steps:
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$PATH:`yarn global bin`"
      - run:
          name: Install Bower
          command: yarn global add bower

      - run:
          name: Git config
          command: |
            git config --global user.email "you@example.com"
            git config --global user.name  "Your Name"

      - checkout

      - run:
          name: Test
          command: cd .. && generator/bin/generate test

      - store_artifacts:
          path: ~/test
          destination: build
