#!/bin/bash

source lib/shared.sh

NEW_DIR="$(pwd)/$1"

lib/01-duplicate.sh "$1"
if [ $? -eq 0 ]; then
  log "template substitutions"
  lib/02-replace.py "$1" "$NEW_DIR"

  if [ $? -eq 0 ]; then
    lib/03-post.sh "$1" "$NEW_DIR"
  fi
fi
